DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS consultants;
DROP TABLE IF EXISTS schedule;


-- Customer data
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(128) NOT NULL,
    dob DATE NOT NULL,
    tel VARCHAR(128) NOT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO customers(name, dob, tel) VALUES
    ('Mr. Smith', '1970-10-23', '012345678'),
    ('Mr. Jones', '1969-09-22', '0563213217'),
    ('Mr. Kernighan', '1942-01-01', '06778231312'),
    ('Mr. Ritchie', '1941-09-09', '043263443543');


-- Consultant data
CREATE TABLE consultants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(128) NOT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO consultants (name) VALUES
    ('Dr. John'),
    ('Dr. Nick'),
    ('Dr. Hibbert'),
    ('Dr. Frasier Crane');



-- Consultant's schedule
CREATE TABLE schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    consultant_id BIGINT,
    start1 TIME,
    end1 TIME,
    start2 TIME,
    end2 TIME,
    slot_duration INT,
    PRIMARY KEY(ID)
);

ALTER TABLE PUBLIC.schedule
ADD FOREIGN KEY(consultant_id)
REFERENCES PUBLIC.consultants(id);

INSERT INTO schedule (consultant_id, start1, end1, start2, end2, slot_duration) VALUES
    (1, '09:00', '12:30', '13:30', '16:30', 15),
    (2, '08:00', '13:30', '15:00', '18:30', 15);




-- Appointment book
CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    consultant_id BIGINT,
    customer_id BIGINT,
    a_date DATE,
    a_time TIME,
    duration TIME,
    complaint VARCHAR(128) NOT NULL,
    PRIMARY KEY(ID)
);

ALTER TABLE PUBLIC.appointments
ADD FOREIGN KEY(customer_id)
REFERENCES PUBLIC.customers(id);

ALTER TABLE PUBLIC.appointments
ADD FOREIGN KEY(consultant_id)
REFERENCES PUBLIC.consultants(id);

INSERT INTO appointments (consultant_id, customer_id, a_date, a_time, duration, complaint) VALUES
    (1, 1, DATEADD('DAY', 1, CURRENT_DATE), '10:30', '00:15', 'wobbly tooth'),
    (1, 2, DATEADD('DAY', 1, CURRENT_DATE), '11:15', '00:30', 'check up'),
    (1, 3, DATEADD('DAY', 1, CURRENT_DATE), '13:15', '00:30', 'root canal'),
    (1, 3, DATEADD('DAY', 1, CURRENT_DATE), '13:45', '00:15', 'root canal');


